name: Manual Trigger Workflow

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch name to build'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}
