name: test-mysql-connection

on:
  push:
    branches: [master]

jobs:
  test-mysql-connection:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: my-secret-pw
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Test MySQL connection
      env:
        MYSQL_PWD: my-secret-pw
      run: |
        mysql -h 127.0.0.1 -P 3306 -u root -e "show databases"
