name: merge_to_develop_sleep

on:
  push:
    branches: [ master ]



  

jobs:
  build_executable_middle_layer:
    runs-on: ubuntu-latest
    concurrency:
      group: deploy_to_develop 
    steps:
      - name: Authenticate to Docker registry
        shell: bash
        run: |
          echo "sleep 150"
          sleep 300
