name: Print Repo Names

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  print_repo_names:
    runs-on: ubuntu-latest

    steps:
      - name: Print Source Repo Name
        run: |
          echo "Source Repository Name: ${{ github.event.pull_request.head.repo.full_name }}"
      - name: Print Target Repo Name
        run: |
          echo "Target Repository Name: ${{ github.event.pull_request.base.repo.full_name }}"
